Online_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(), name='cart_remove'),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models

from .managers import UserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=225, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=225)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


    @property
    def is_staff(self):
        return self.is_admin

home/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=225)
    slug = models.SlugField(max_length=225, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    name = models.CharField(max_length=225)
    descriptions = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('home:product_detail', args=[self.slug,])

orders/models.py
from accounts.models import User
from django.db import models
from home.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    crested = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from .models import User


class UserCreationsForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'phone_number', 'full_name']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('password dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text='you can change password <a href=\"../password/\" this form>')

    class Meta:
        model = User
        fields = ['email', 'phone_number', 'full_name', 'password', 'last_login']

accounts/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from orders.form import CartAddForm
from .models import Product

class HomeView(View):
    def get(self, request):
        products = Product.objects.filter(available=True)
        return render(request, 'home/home.html', {'products': products})


class ProductDetailView(View):
    def get(self, request, slug):
        form = CartAddForm()
        product = get_object_or_404(Product, slug=slug)
        return render(request, 'home/detail.html', {'product':product, 'form':form})

orders/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from home.models import Product
from .cart import Cart
from .form import CartAddForm
from .models import Order, OrderItem


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderDetailView(View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, id = order_id)
        return render(request, 'orders/order.html' , {'order':order})



class OrderCreateView(View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user = request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price = item['price'], quantity= item['quantity'])
        cart.clear()
        return redirect('orders:order_detail', order.id)

home/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}
<style>
    .container{
        display: grid;
        margin-top: 50px;
        grid-template-columns: 500px 500px;
    }
</style>
    <div class="container">
        <div class="row align-items-center">
            <img class="cart-img" src="{{ product.image.url }}">
        </div>
        <div class="py-5">
            <h2>{{ product.name }}</h2>
            <small> created in: {{ product.created }}</small><hr>
            درباره محصول:
            <p style="text-align:left" class="text-start py-3"> {{ product.descriptions }} </p>
            <br/><br>

            <h5 class="text-black"><small>{{ product.price }} تومان</small></h5><br/><br/>
            <form action="{% url 'orders:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ form }}<br/>
                <button class="add_to_cart">
                افزودن به سبد
                </button>
            </form>
        </div>

    </div>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block content %}

<section id="bgshow">
    <div class="bgshow-main text-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="mt-4 pt-4 display-4">گروه تجاری هرمس</h2>
                    <p class="lead text-center py-3">تجربه زندگی در آینده</p>
                </div>
                <div class="col-lg-6"></div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container">
        <p class=" lead py-5"> پر فروش ترین ها</p>
        <div class="row">
            {% for product in products %}
                <div class="col-6 col-sm-6 col-md-3 col-lg-3 mb-4">
                    <div class="card h-100 shadow-sm">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                        </a>
                        <div class="card-body text-center">
                            <h3 class="h6 card-title">
                                <a href="{{ product.get_absolute_url }}" class="text-decora-none text-dark">{{ product.name }}</a>
                            </h3>
                            <p class="text-muted md-0">{{ product.price }} تومان</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-5 rtl">
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">نام کالا</th>
                <th scope="col">تعداد</th>
                <th scope="col">قیمت واحد</th>
                <th scope="col">قیمت کل</th>
                <th scope="col">حذف</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td><a href="{% url 'orders:cart_remove' item.product.id %}">حذف کالا</a></td>
              </tr>
              {% endfor %}
            </tbody>
            <tr>
              <td>جمع کل</td>
              <td colspan="4"></td>
              <td>{{ cart.get_total_price }}</td>
            </tr>
        </table>

        <a href="{% url 'orders:order_create' %}" class="btn btn-primary">تایید</a>
    </div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{% block content %}

    <div class="container py-5">
        <h3>مبلغ نهایی</h3>
        <p>{{ order.get_total_price }} تومان </p>
        <a href="##" class="btn btn-success">پرداخت</a>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>Hermes shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        {% block extra_headers %} {% endblock %}

    <style>
        body {
            font-family: sans-serif;

        }

         .add_to_cart{
            border: none;
            background-color: rgb(230, 25, 25);
            color: white;
            border-radius: 8px;
            padding: 6px 35px;
         }
         #bgshow{
            position: relative;
            min-height: 100vh;
            background: url(../media/static/images/1.png) no-repeat center center;
            background-size: cover;
         }
        .bgshow-main{
            text-align: left;
            position: absolute;
            left: 0%; top: 0%;
            height: 100%;
            width: 100%;
            display: flex;
            align-items: start;
            justify-content: flex-start;
            padding-left: 0px;
            margin-top: 50px;
            direction: ltr;

        }
        .cart-img{
            width: 400px;
        }
    </style>
</head>
<body>
    {% include 'inc/navbar.html' %}

    <main class="container-fluid px-0">
        {% block content %}  {% endblock %}
    </main>

    <footer class="bg-light text-center py-4 mt-5 ">
        <p class="mb-1">گروه تجاری هرمس©</p>
        <small>ساخته شده توسط شرکت راستین</small>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/inc/navbar.html
 <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="mainNavbar">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active text-white" href="{% url 'home:home' %}">خانه</a>
                </li>
            </ul>
        </div>
    </div>

 <style>
     header{
        positions: fixed;
        top: 0; left: 0; right:0;
        padding: 2rem;
        background: #272525;
        display: flex;
        align-items: center;
        justify-content: space-between;
        z-index: 1000;
        box-shadow: 0 .5rem 1rem rgb(0 , 0 , 0, .1)
     }

     header .navbar1 a{
        font-size: 1.1rem;
        color: #fff;
        padding: 1.5rem;
     }

     header .logo{
        font-size: 1.5rem;
        color: #666;
        font-weight: bold;
     }


 </style>

 <header>

    <a href="#" class="logo">HERMES<span>.</span></a>

    <nav class="navbar1">
        <a href="{% url 'home:home' %}">HOME</a>
        <a href="#">ABOUT</a>

        <a href="{% url 'orders:cart' %}">
            <i class="bi bi-cart3"></i>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger fas fa-shopping-cart">
                {{ cart|length }}
            </span>
        </a>
    </nav>
 </header>